---
version: 1
tasks:
  $map:
    - name: ci-admin check run
      symbol: check
      description: "Run `ci-admin check` to validate the latest changes"
      commandSuffix: >-
        python setup.py develop &&
        ci-admin check
        --environment firefoxci
        --ci-configuration-repository "${repository.url}"
        --ci-configuration-revision "${push.revision}"
  each(cfg):
    taskGroupId: "${ownTaskId}"
    taskId: "${ownTaskId}"
    schedulerId: 'ci-level-${repository.level}'
    provisionerId: ci-t
    workerType: linux
    priority: low
    created: {$fromNow: ''}
    deadline: {$fromNow: '1 day'}
    expires: {$fromNow: '14 days'}
    payload:
      image: 'python:3.6'
      command:
        - /bin/bash
        - '-c'
        - >-
            hg clone https://hg.mozilla.org/ci/ci-admin ci-admin &&
            cd ci-admin &&
            pip install -r requirements/base.txt &&
            ${cfg.commandSuffix}
      maxRunTime: 3600
    scopes: []
    extra:
      treeherder:
        symbol: "${cfg.symbol}"
        jobKind: "test"
        machine:
          platform: "on-push"
        productName: ci-admin
    routes:
      - "tc-treeherder.v2.${repository.project}.${push.revision}.${push.pushlog_id}"
    metadata:
      name: "${cfg.name}"
      description: "${cfg.description}"
      owner: nobody@mozilla.org
      source: 'https://hg.mozilla.org/ci/ci-admin'
