# This file contains configuration for each of the environments in which
# ci-admin/ci-configuration apply.
#
# Structure
# ---------
#
# Each environment, keyed by its name, must have a rootUrl.  The credentials
# are checked against that rootUrl to ensure that it is being applied in the
# right place.
#
# Each environment can also have `modify_resources`, a list of modifications to
# make to the generated resources.  Such modifications are defined in ci-admin,
# and exist to help configure minor differences between environments, such as
# to prevent a staging environment from carrying a full production workload.
---
staging:
    root_url: https://stage.taskcluster.nonprod.cloudops.mozgcp.net
    modify_resources:
      # we do not want hooks to trigger on a schedule in staging, as that adds
      # lots of load (e.g., building nightlies).  They can be triggered
      # manually if needed for testing.
      - remove_hook_schedules
      # similarly, we do not want to bind hooks to exchanges, as those exchanges
      # likely do not exist here
      - remove_hook_bindings
      # Remove minimum capacity of all worker-types, since staging clusters
      # do not have enough load to justify always-on workers.
      - remove_worker_min_capacity
      # Remove gcp-provider workers from firefox-ci cluster,
      # since all the currently used non-aws providers
      # don't exist in firefox-ci.
      - remove_gcp_workers
    worker_manager:
        providers:
            aws:
                implementation: aws
            fxci-level1-gcp:
                implementation: google
            fxci-level2-gcp:
                implementation: google
            fxci-level3-gcp:
                implementation: google
    aws_config:
        availability-zones:
            by-region:
                us-east-1:
                    - "us-east-1a"
                    - "us-east-1b"
                    - "us-east-1c"
                    - "us-east-1d"
                    - "us-east-1e"
                    - "us-east-1f"
                us-west-1:
                    - "us-west-1a"
                    - "us-west-1b"
                us-west-2:
                    - "us-west-2a"
                    - "us-west-2b"
                    - "us-west-2c"
        subnet-id:
            by-availability-zone:
                us-east-1a: subnet-0c938056fff37f311
                us-east-1b: subnet-00d682e89c23d7a86
                us-east-1c: subnet-006eff582598db077
                us-east-1d: subnet-01454cff97aa89f34
                us-east-1e: subnet-04003ab20f583059b
                us-east-1f: subnet-0d8c0e26a6194119c
                us-west-1a: subnet-0a30116fa0be3bc99
                us-west-1b: subnet-01aac9d0ea7efdbc4
                us-west-2a: subnet-06b091438ea962936
                us-west-2b: subnet-00927443142f01ddf
                us-west-2c: subnet-0ab2f88a3fa4ab7a0
        security-groups:
            by-security:
                untrusted:
                    by-region:
                        "us-east-1": ["sg-01738525fc9991bd0"]
                        "us-west-1": ["sg-0f52b4554cfc115e7"]
                        "us-west-2": ["sg-07ca8c96f1574d42b"]
                trusted:
                    by-region:
                        "us-east-1": ["sg-7aca300a"]
                        "us-west-1": ["sg-5ce02b3a"]
                        "us-west-2": ["sg-a0d6beda"]
        invalid_instances: []
    google_config:
        zones:
            by-region:
                us-central1: ['us-central1-a', 'us-central1-b','us-central1-c','us-central1-f']

firefoxci:
    root_url: https://firefox-ci-tc.services.mozilla.com
    # no modifications in production, please!
    modify_resources:
      # Remove gcp-provider workers from firefox-ci cluster,
      # since all the currently used non-aws providers
      # don't exist in firefox-ci.
      - remove_gcp_workers
    worker_manager:
        providers:
            aws:
                implementation: aws
            fxci-level1-gcp:
                implementation: google
            fxci-level2-gcp:
                implementation: google
            fxci-level3-gcp:
                implementation: google
    aws_config:
        availability-zones:
            by-region:
                us-east-1:
                    - "us-east-1a"
                    - "us-east-1b"
                    - "us-east-1c"
                    - "us-east-1d"
                    - "us-east-1e"
                    - "us-east-1f"
                us-west-1:
                    - "us-west-1b"
                    - "us-west-1c"
                us-west-2:
                    - "us-west-2a"
                    - "us-west-2b"
                    - "us-west-2c"
                eu-central-1:
                    - eu-central-1a
                    - eu-central-1b
                    - eu-central-1c
        subnet-id:
            by-availability-zone:
                us-east-1a: "subnet-566e060c"
                us-east-1b: "subnet-f2c93496"
                us-east-1c: "subnet-c52454e9"
                us-east-1d: "subnet-e7e6ccaf"
                us-east-1e: "subnet-deb5a8e2"
                us-east-1f: "subnet-7f720d73"
                us-west-1b: "subnet-7641632e"
                us-west-1c: "subnet-48a9b82c"
                us-west-2a: "subnet-d948b6bf"
                us-west-2b: "subnet-2eaaba67"
                us-west-2c: "subnet-540a9f0f"
                eu-central-1a: subnet-935645fb
                eu-central-1b: subnet-6988da13
                eu-central-1c: subnet-114d525b
        security-groups:
            by-security:
                untrusted:
                    by-region:
                        "us-east-1": ["sg-12cd3762"]
                        "us-west-1": ["sg-caed26ac"]
                        "us-west-2": ["sg-2728435d"]
                windows-untrusted:
                    by-region:
                        "us-east-1": ["sg-0dc9337d", "sg-27d72d57"]
                        "us-west-1": ["sg-5be3283d", "sg-fee02b98"]
                        "us-west-2": ["sg-09d6be73", "sg-3bd7bf41"]
                        "eu-central-1": ["sg-c03e0eab", "sg-e43d0d8f"]
                trusted:
                    by-region:
                        "us-east-1": ["sg-7aca300a"]
                        "us-west-1": ["sg-5ce02b3a"]
                        "us-west-2": ["sg-a0d6beda"]
        invalid-instances:
            - zones: ["us-east-1e"]
              families: ["m5", "m5a", "m5d", "c5", "c5d", "r5a", "z1d"]
            - zones: ["us-east-1b", "us-east-1f"]
              families: ["r3", "m3", "c3"]
            - zones: ["us-east-1a", "us-east-1b", "us-east-1d", "us-east-1e"]
              families: ["r5ad"]
    google_config:
        zones:
            by-region:
                us-central1: ['us-central1-a', 'us-central1-b','us-central1-c','us-central1-f']
