---
trust-domain: ci
treeherder:
    group-names:
        'I': 'Docker Image Builds'
        'check': 'config checks'
        'unit': 'unit tests'

task-priority: low

taskgraph:
    repositories:
        config:
            name: ci-configuration
            project-regex: ci-configuration.*
            default-repository: https://hg.mozilla.org/ci/ci-configuration
            default-ref: default
            type: hg

workers:
    aliases:
        images:
            provisioner: 'ci-{level}'
            implementation: docker-worker
            os: linux
            worker-type: images-gcp
        t-linux:
            provisioner: 'ci-t'
            implementation: docker-worker
            os: linux
            worker-type: linux-gcp
